### ISSUE TITLE
Add Deb8 to this package?

### ISSUE THREAD

**Issue by ghost** [BunsenLabs/bunsen-themes#1]
@bunsenLabs As the subject says: Should I add Deb8 to this very package?

**Comment by johnraff** [comment]
That's one for @hhhorb 

...and thank you for this!

**Comment by hhhorb** [comment]
I haven't updated Deb8 to be in line with these themes. I'm thinking of doing a second theme pack with a bunch of colors, I suggest adding Deb8 to that.

**Comment by ghost** [comment]
Good, thanks for the clarification!
