### ISSUE TITLE
Lxde volume icon wrongly themed

### ISSUE THREAD

**Issue by enricocid** [BunsenLabs/bunsen-themes#10]
The volume panel in lxpanel is looking bad in dark themes as You can see from screenshot :)

![istantanea_2015-09-21_11-05-10](https://cloud.githubusercontent.com/assets/7274841/9988545/e2316c5a-6051-11e5-98bc-de3628761ba5.png)

**Comment by hhhorb** [comment]
I'll check it out and post back. What theme and icon sets are you using? BTW, I can't test on Arch ATM.

**Comment by enricocid** [comment]
i have this problem with all dark variants of bunsen theme 
the icons are numix circle 
but the problem is not the icon on the panel (the title is wrong) but the volume panel 
thanks

**Comment by hhhorb** [comment]
Using the Hydrogen RC1 64 bit ISO instaled to VirtualBox, it looks fine using Bunsen-Blue-Dark...

![screenshot - 09212015 - 01 22 05 pm](https://cloud.githubusercontent.com/assets/10426086/9999493/b105d55e-6064-11e5-80be-e903d19538fd.png)

I'll install numix cirlce icons and check again, but our volume applets look so different. Which one are you using?

**Comment by enricocid** [comment]
this is volume icon applet, I know
but I'm using the applet provided by lxde and lxpanel :)

**Comment by hhhorb** [comment]
Ah, OK. I can check this later today.

**Comment by enricocid** [comment]
don't worry , take your time
it seems it is a common problem in dark themes (i tried menda dark, Dorian etc etc , and I have the same problem)

**Comment by hhhorb** [comment]
Sorry for the long delay.

This seems like an issue for lxpanel. Sorry.

**Comment by enricocid** [comment]
yeah, I understand, in effect I have the same problem on all black theme :( no problem, I will use the volumeicon indicator instead of the stock one ;)
thanks
