### ISSUE TITLE
Pictures say more than 1000 words

### ISSUE THREAD

**Issue by Tset-Noitamotua** [BunsenLabs/bunsen-themes#15]
Please add screenshots or links to them to this repo. ;-)

**Comment by hhhorb** [comment]
Sorry for the delay, I've had a brutal fall and winter.

I should add screenshots, but BunsenLabs is more about customization than the default theme (something Distrowatch didn't seem to grasp in their review of us).

https://www.bunsenlabs.org/
https://forums.bunsenlabs.org/viewforum.php?id=8

Also, we are a small team who donate our spare time to the project. nevertheless, I'll upload a scrot of the default theme, Bunsen, to this repo.

Thanks!

**Comment by capn-damo** [comment]
http://bunsenlabs.deviantart.com/art/BunsenLabs-default-theme-546407161
