### ISSUE TITLE
Bunsen theme Terminator tabs are not visually selected

### ISSUE THREAD

**Issue by aponad** [BunsenLabs/bunsen-themes#6]
Currently there is no way to tell which tab is selected.
![selection_099](https://cloud.githubusercontent.com/assets/445242/8564079/ff699816-254f-11e5-8895-e5b0fa9a5eba.png)

If we uncomment this lines (https://github.com/BunsenLabs/bunsen-themes/blob/master/Bunsen/gtk-2.0/gtkrc#L254-L256):
![selection_100](https://cloud.githubusercontent.com/assets/445242/8564081/054a4abe-2550-11e5-8649-bbe337f540cb.png)

As I understand the selected tab height should have changed like in shutter or pcmanfm, but terminator tabs are to compact, maybe it is a terminator bug.

**Comment by hhhorb** [comment]
Right, that's some nice bugshooting there, Tex! I'll test and push this fix, thanks!

**Comment by hhhorb** [comment]
Excellent, thank you. This effects all the light-background colored themes at least. I'll push the fix ASAP.

**Comment by hhhorb** [comment]
Again, great catch. Those line were already uncommented in the dark themes. The fixes are in, closing this issue.
