### ISSUE TITLE
Bunsen theme LibreOffice Calc Sheet size

### ISSUE THREAD

**Issue by aponad** [BunsenLabs/bunsen-themes#7]
Hi,
Using Bunsen theme LibreOffice Calc Sheet looks like

![selection_105](https://cloud.githubusercontent.com/assets/445242/8956360/bf85d156-35fd-11e5-87ae-79a38afbeae8.png)

To fix this we need to uncomment this line:
https://github.com/BunsenLabs/bunsen-themes/blob/master/Bunsen/gtk-2.0/gtkrc#L63

Result:
![selection_104](https://cloud.githubusercontent.com/assets/445242/8956368/d378bf02-35fd-11e5-9562-cb4212abcd54.png)

**Comment by hhhorb** [comment]
I don't use Libre Calc, have you found uncommenting that line to have any undesirable effects? I mean in other applications, too.

Also, you see my comments there. Does uncommenting the next 2 lines do anything that you can tell?

**Comment by aponad** [comment]
Not in any application I use (filezilla, firefox, chrome, sublime, terminator, virtualbox, pcmanfm, smplayer, gpodder, libreoffice, shutter)

Tried uncommenting those lines could not see any difference.

I think here is the documentation for this parameters:
https://wiki.gnome.org/Attic/GnomeArt/Tutorials/GtkThemes/GtkScrollbar

**Comment by aponad** [comment]
Actually scrollbars got bigger
Before:
![selection_108](https://cloud.githubusercontent.com/assets/445242/8978023/05c832c2-36a7-11e5-9b01-e4b87652dacb.png)

After:
![selection_109](https://cloud.githubusercontent.com/assets/445242/8978025/0ad97578-36a7-11e5-94ff-2d4eab764f06.png)

**Comment by ghost** [comment]
@hhhorb Reduce slider-width so that it goes well with the overall theme; set activate-slider=1 and trough-border=0?

**Comment by hhhorb** [comment]
I'll install LibreOffice this evening and experiment. I'd like to live with the changes for at least a couple of days to test and then I'll push the changes.

@wonderfulll, thanks for this report!

**Comment by hhhorb** [comment]
I'm sorry, finally testing this and the first scrot in the first post is not what I see. @capn-damo, can you help here?

**Comment by capn-damo** [comment]
@hhh Same as you. 

I don't see the narrow tabs and slider, and commenting/uncommenting those lines has no obvious effect AFAICS.

**Comment by hhhorb** [comment]
Thanks for confirming, damo. I'll leave this issue open for a while longer just in case.
