### ISSUE TITLE
Resize issues with BL themes and gtk3 apps

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-themes#9]
Evince window will only resize by dragging from the top edge (A-Rclick + drag works though)

Transmission-gtk & synaptic can be resized by dragging edges or corners, but only to a minimum width. (Min width with A-Rclick + drag as well)

Adwaita theme works OK

**Comment by capn-damo** [comment]
Seems that a fix to CSD is needed. I've tested with `Bunsen/gtk-3.0/gtk-widgets.css`, and added a margin size:

```
/* CSD hack */

.window-frame, .window-frame:backdrop {
 box-shadow: 0 0 0 black;
 border-style: none;
 margin: 10;
 border-radius: 0;
}
```

This now allows edges on Evince windows to be dragged with the mouse.

**Comment by hhhorb** [comment]
@capn-damo. please test transmission and synaptic as well and commit your changes if everything looks good. Leave this issue open while we continue to test and get user feedback.

Thanks for bug-shooting, man!

**Comment by capn-damo** [comment]
@hhhorb 
The other apps I tested could still be resized by dragging edges, but there is a minimum size of the windows, which must be an application config setting. That is a separate issue I think (maybe not an issue at all).

Presumably it is possible to have the fix specifically for Evince, in case it messes up other apps?

You want this edit to all the BL themes, if it works on all of them?

**Comment by Hjdskes** [comment]
> but there is a minimum size of the windows, which must be an application config setting. That is a separate issue I think (maybe not an issue at all).

The header bar used by these applications dictates a minimal width. Not sure if this can be overriden with the theme...

**Comment by hhhorb** [comment]
Yeah, let's not worry about min-window size (gtk2 apps have this too).

@capn-damo, it'll need to go in all the BL themes. We could wait a week to do some testing or else include it for all gtk3 apps and revise it later if needed. Either is fine by me.

**Comment by capn-damo** [comment]
Tested `/*CSD*/` hack edit with all Bunsen\* themes:

synaptic and transmission-gtk have no change to the normal edge dragging behaviour previously shown;
evince now has the desired edge dragging behaviour.

Pushed the changes to `gtk-3.0/gtk-widgets.css` to `bunsen-themes`.

**Comment by hhhorb** [comment]
Thank you Damo, I'm leaving this issue open for a week as a reminder to myself to do some tests.

**Comment by damufo** [comment]
This work for me.
Thanks!
